/*
 * DO NOT EDIT THIS FILE BY HAND!  It is generated by MKfallback.sh.
 */

#include "term.h"

const TERMTYPE *_nc_fallback(const char *name)
{
	/* the fallback list is empty */
	return((TERMTYPE *)NULL);
}
