#!/bin/sh
# $Id: tdlint,v 1.2 1996/07/15 00:47:21 tom Exp $
#
# Lint-script that allows user's own lint libraries, in addition to the ones
# installed in the system.
#
OPT=""
DIRS=""
LIBS=""
FILES=""
ARCH=`uname -s`
if test -z "$ARCH" ; then
	echo '? uname not found'
	exit 1
else
	case $ARCH in
	AIX)	set - $* -Nn4000
		;;
	IRIX)	set - $* -n -lc
		;;
	SunOS)
		case `uname -r` in
		5.*)	ARCH=Solaris
			set - $* -n -lc
			;;
		esac
		;;
	esac
fi
# LIBDIR=$HOME/lib/$ARCH/lint ;export LIBDIR
for p in $HOME/lib/$ARCH/lint /usr/lib/lint /usr/lib
do
	if [ -d $p ]
	then
		DIRS="$DIRS $p"
	fi
done
#
while [ $# != 0 ]
do
	case $1 in
	-D*\"*)	;;
	-L*)
		DIRS="`echo $1|sed -e 's/^-L//'` $DIRS"
		;;
	-l*)
		lib="llib-l`echo $1 | sed -e 's/^-l//'`.ln"
		found=no
		for p in $DIRS
		do
			echo -n testing $p/$lib
			if [ -f $p/$lib ]
			then
				LIBS="$LIBS $p/$lib"
				echo " (ok)"
				found=yes
				break
			fi
			echo
		done
		if [ $found = no ]
		then
			echo "ignored library $1"
		fi
		;;
	-n)	if [ -z "$OPT" ]
		then
			OPT="-I."
		fi
		OPT="$OPT $1"
		;;
	-*)	OPT="$OPT $1"
		;;
	*)
		FILES="$FILES $1"
		;;
	esac
	shift
done
#
eval lint $OPT $FILES $LIBS
