# change to -ldcurses if you want to do any debugging

# Use these flags to debug with the production library
LDFLAGS = -L$(LIB) -lncurses

# Use these flags to debug with the source directory library
#CFLAGS = -g -I../src
#LDFLAGS = -L../src ../src/libdcurses.a

TESTS = \
	battle \
	blue \
	bs \
	copy \
	firework \
	gdc \
	hanoi \
	knight \
	newdemo \
	ncurses \
	over \
	rain \
	testcurs \
	worm \
	tclock \
	view \
	xmas 

all: $(TESTS) 

battle: battle.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
blue: blue.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
bs: bs.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
copy: copy.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
firework: firework.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
gdc: gdc.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
hanoi: hanoi.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
knight: knight.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
ncurses: ncurses.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
newdemo: newdemo.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
over: over.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
rain: rain.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
testcurs: testcurs.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
worm: worm.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
tclock: tclock.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -lm -o $@
view: view.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@
xmas: xmas.c
	$(CC) $(CFLAGS) $@.c $(LDFLAGS) -o $@

clean:
	rm -rf *.o trace t $(TESTS)

clobber: clean
	rm -rf Config.* Makefile
	@echo "You'll have to reconfigure by running src/Configure"

